server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: weatherSerivce
          uri: lb://WEATHER-SERVICE
          predicates:
            - Path=/api/v1/weather/**
        - id: loggingSerivce
          uri: lb://LOGGING-SERVICE
          predicates:
            - Path=/api/v1/logging/**


